# Generated by Django 4.0.3 on 2022-03-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marvels_Studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='default title', upload_to='poster/', verbose_name='Постер'),
        ),
    ]
