# Generated by Django 4.0.3 on 2022-06-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marvels_Studio', '0002_movie_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Famous_actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, verbose_name='Имя актёра')),
                ('age', models.CharField(max_length=10, verbose_name='Возраст актёра')),
                ('date', models.DateTimeField(max_length=20, verbose_name='День рождение')),
            ],
            options={
                'verbose_name': 'Известный актёр',
                'verbose_name_plural': 'Известные актёры',
            },
        ),
    ]
