# Generated by Django 4.0.3 on 2022-06-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marvels_Studio', '0003_famous_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='famous_actors',
            name='image',
            field=models.ImageField(default='default title', upload_to='famous/', verbose_name='Фотография создателя Marvel'),
        ),
        migrations.AlterField(
            model_name='famous_actors',
            name='age',
            field=models.CharField(max_length=3, verbose_name='Возраст актёра'),
        ),
        migrations.AlterField(
            model_name='famous_actors',
            name='date',
            field=models.DateField(max_length=20, verbose_name='День рождение'),
        ),
    ]
