# Generated by Django 4.0.5 on 2022-09-02 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Marvels_Studio', '0005_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
