# Generated by Django 4.0.5 on 2022-09-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marvels_Studio', '0006_movie_is_published_movie_time_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textinfo', models.TextField(verbose_name='Информация о нас')),
                ('date_create', models.DateTimeField(verbose_name='Дата публикации')),
                ('published', models.BooleanField(unique=True)),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.AlterField(
            model_name='movie',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
